##################
# MedScore Configuration File
##################

# --- Main Input/Output Files ---
# input_file: "data/AskDocs.demo.jsonl"
output_dir: "results"
response_key: "response"

# --- Decomposition Configuration ---
decomposer:
  type: "medscore"  # Options: medscore, factscore, dndscore, custom
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
  server_path: "https://api.together.xyz/v1"
  api_key: !env TOGETHER_API_KEY

# --- Verification Configuration ---
verifier:
  type: "internal" # Options: internal, medrag, provided
  model_name: "gpt-4o"
  server_path: "https://api.openai.com/v1"  #set the server_path to your GPU server when using HuggingFace models via vLLM server_path
